---
title: "spaghetti"
author: "Kaija Gahm"
date: "1/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r, echo = F}
library(tidyverse)
source("spaghetti_functions.R")
```

# Steps
## 1. Take a look at the box of pasta and the pot of water
```{r}
box # the box contains pasta that is not yet cooked
pot # the pot is empty: contains only cold air.
```

## 2. Fill the pot with water
```{r}
pot <- fill(pot)
pot
```

## 3. Heat the water
```{r}
pot <- pot %>% cook(what = "water", minutes = 10)
pot
```

## 4. Put in the pasta
```{r}
pot <- pot %>% add(from = box, .)
box
pot
```

## 5. Cook the pasta
```{r}
pot

pot <- pot %>% cook("water", 10)
pot
```

## 6. Serve the pasta
```{r}
pasta <- drain(pot)
pasta
```

# Summary
## The traditional way to do it:
```{r}
pot <- data.frame(ingredient = as.character("air"), cooked = 0)
pasta <- drain(cook(add_pasta(cook(fill(pot), what = "water", minutes = 10)), what = "pasta", minutes = 10))
pasta
```

## The way to do it with the dplyr pipe:
```{r}
pasta <- pot %>% 
  fill() %>% 
  cook(what = "water", minutes = 10) %>%
  add_pasta() %>%
  cook(what = "pasta", minutes = 10) %>%
  drain()
pasta
```

